### ISSUE TITLE
--input-directory fails on sequence folder

### ISSUE THREAD

**Issue by oliverdrechsel** [pirovc/ganon#105]
Hi,

i downloaded data via genome_updater

```
$ Tools/genome_updater/genome_updater.sh -g "taxids:1386" -d "refseq" -l "Chromosome" -f "genomic.fna.gz,assembly_report.txt" -t 36 -o References/all_bacillus_chromosome/ -r -a
----------------------------------------
      genome_updater version: 0.2.0
----------------------------------------
Mode: NEW - DOWNLOAD
Working directory: [...]
----------------------------------------
Downloading assembly summary
 - 4480/4579 entries removed [RefSeq category: all, Assembly level: Chromosome, Version status: latest]
 - 99 entries available
 - Downloading 198 files with 36 threads
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

 - 185/198 files successfully downloaded
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

 - Sequence accession report written [...]

Downloading current Taxonomy database [...]
 - Done

Downloading current Taxonomy database [...]
 - Done

# 185/198 files successfully obtained
 - 13 file(s) failed to download. Please re-run your command with -i to fix it again
```

Missing files were fixed successfully with `-i` setting. Thanks for this option!

Start to build ganon index fails.
I tried different levels of `--input-directory` meaning going one or two levels up, but to no avail.

```
$ ganon build \
--db-prefix References/Bacillus_Ganon \
--input-directory References/all_bacillus_chromosome/2019-12-03_17-47-21/files/ \
--input-extension *.fna.gz
Extracting accessions... Traceback (most recent call last):
  File "[...]/bin/ganon", line 1116, in <module>
    main()
  File "[...]/bin/ganon", line 211, in main
    taxsbp_input_file, ncbi_nodes_file, ncbi_merged_file, ncbi_names_file = prepare_files(args, tmp_output_folder, use_assembly, ganon_get_len_taxid_exec)
  File "[...]/bin/ganon", line 618, in prepare_files
    taxsbp_input_file = retrieve_ncbi(tmp_output_folder, args.input_files, args.threads, ganon_get_len_taxid_exec, args.seq_info, use_assembly)
  File "[...]/bin/ganon", line 728, in retrieve_ncbi
    run_get_header = "cat {0} {1} | gawk 'BEGIN{{FS=\" \"}} /^>/ {{print substr($1,2)}}'".format(" ".join(files), "| zcat" if files[0].endswith(".gz") else "")
IndexError: list index out of range
```
The same command using `--input-files` succeeds.

```
 $ ganon build \
--db-prefix References/Bacillus_Ganon \
--input-files References/all_bacillus_chromosome/2019-12-03_17-47-21/files/*.fna.gz

Extracting accessions... 260 accessions retrieved. Done. Elapsed time: 4.39 seconds.
Retrieving sequence lengths and taxid from NCBI E-utils... Done. Elapsed time: 4.38 seconds.
Downloading taxdump... Done. Elapsed time: 35.49 seconds.
Estimating best bin length... 3635902bp. Done. Elapsed time: 4.09 seconds.
Running taxonomic clustering (TaxSBP)... 165 bins created. Done. Elapsed time: 3.65 seconds.
Approximate (upper-bound) # unique k-mers: 3635884
Bloom filter calculated size with fp<=0.05: 543.3170MB (23737884 bits/bin * 192 optimal bins [165 real bins])
Building index (ganon-build)...

ganon-build processed 260 sequences (509.441 Mbp) in 155.684 seconds (0.100203 Kseq/m, 196.337 Mbp/m)
 - 260 sequences and 165 bins defined on References/Bacillus_Ganon_tmp/acc_bin.txt
 - 260 sequences (0 invalid) were read from the input sequence files.
 - 260 valid sequences in 165 bins were written to References/Bacillus_Ganon.filter
Done. Elapsed time: 156.48 seconds.
Building database files... Done. Elapsed time: 5.83 seconds.
Total elapsed time: 216.89 seconds.

```

I guess I did something wrong, but could not identify it by myself.

**Comment by pirovc** [comment]
Hi @oliverdrechsel 

When using the `--input-directory` and `--input-extension` please do not use the start (`*`) expansion.

`ganon build --db-prefix References/Bacillus_Ganon --input-directory References/all_bacillus_chromosome/2019-12-03_17-47-21/files/ --input-extension .fna.gz`

Best
Vitor
