### ISSUE TITLE
ganon report UnboundLocalError: local variable 'tax' referenced before assignment

### ISSUE THREAD

**Issue by marade** [pirovc/ganon#273]
$ ganon report -x skip --report-type reads -i classify_results.rep -o classify_res
- - - - - - - - - -
   _  _  _  _  _
  (_|(_|| |(_)| |
   _|   v. 2.0.0
- - - - - - - - - -
Generating report(s)

Total valid files: 1

Downloading and parsing skip taxonomy
 - done in 0.00s.

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/py310/bin/ganon", line 33, in <module>
    sys.exit(load_entry_point('ganon==2.0.0', 'console_scripts', 'ganon')())
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/ganon/ganon.py", line 53, in main_cli
    sys.exit(0 if main() else 1)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/ganon/ganon.py", line 44, in main
    ret = report(cfg)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/ganon/report.py", line 68, in report
    default_ranks = [tax.root_name] + cfg.choices_default_ranks
UnboundLocalError: local variable 'tax' referenced before assignment

**Comment by marade** [comment]
$ ganon report -x skip --report-type reads -i classify_results.rep -o classify_res --db-prefix Pro
File not found: Pro.tax

**Comment by pirovc** [comment]
Fixed in v2.0.1 #281

**Comment by marade** [comment]
Thanks!
