### ISSUE TITLE
System exit when trying to build index with raptor

### ISSUE THREAD

**Issue by ksavhughes** [pirovc/ganon#275]
Hi ganon team,

I'm not really sure what is going on here. Can you help me?

error message:
Parse finished - skipping
Building index (raptor)
Traceback (most recent call last):
  File "/home/karsav1511/.conda/envs/ganon/bin/ganon", line 33, in <module>
    sys.exit(load_entry_point('ganon==2.0.0', 'console_scripts', 'ganon')())
  File "/home/karsav1511/.conda/envs/ganon/lib/python3.10/site-packages/ganon/ganon.py", line 53, in main_cli
    sys.exit(0 if main() else 1)
  File "/home/karsav1511/.conda/envs/ganon/lib/python3.10/site-packages/ganon/ganon.py", line 36, in main
    ret = build_custom(cfg)
  File "/home/karsav1511/.conda/envs/ganon/lib/python3.10/site-packages/ganon/build_update.py", line 365, in build_custom
    Path(build_output_folder + new_target + exts).symlink_to(first_file)
  File "/home/karsav1511/.conda/envs/ganon/lib/python3.10/pathlib.py", line 1255, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
FileExistsError: [Errno 17] File exists: '/ourdisk/hpc/hofmanlmamr/karsav1511/auto_archive_notyet/tape_2copies/RefSeq/ganonRefSeqLim3/refs/bacteria3/GCF_006777585.1_ASM677758v1_genomic.fna.gz' -> 'bacteria3_files/build/2078.fna.gz'

**Comment by pirovc** [comment]
Hi, thanks for reporting. To avoid this issue, delete the `build` folder inside of `bacteria3_files` and try again. There are some temporary files created from previous attempts generating this error. This is a bug and will be fixed soon.

**Comment by ksavhughes** [comment]
Thank you!

**Comment by pirovc** [comment]
Fixed in v2.0.1 #281
